org: fundamentaldog
console: true
service: poc-serverless

plugins:
  - serverless-dotenv-plugin
custom:
  vpc:
    securityGroupIds:
      - sg-0d7788682adbb9247
    subnetIds:
      - subnet-0ee90dedf395a7fd7
      - subnet-091eb253d360f2020
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  # iamRoleStatements:
  #   - Effect: Allow
  #     Action:
  #       - lambda:InvokeFunction
  #     Resource: "*"

  stage: dev
  region: ap-southeast-1

functions:
  contact:
    handler: handler.contact
    vpc: ${self:custom.vpc}
    timeout: 30
    events:
      - http:
          path: contacts
          method: get
          cors: true
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:ap-southeast-1:836503426071:userpool/ap-southeast-1_5hkd0Ax65
      - http:
          path: contacts/{id}
          method: get
          request:
            parameters:
              paths:
                id: true
          cors: true
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:ap-southeast-1:836503426071:userpool/ap-southeast-1_5hkd0Ax65
      - http:
          path: contacts
          method: post
          cors: true
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:ap-southeast-1:836503426071:userpool/ap-southeast-1_5hkd0Ax65
      - http:
          path: contacts/{id}
          method: put
          request:
            parameters:
              paths:
                id: true
          cors: true
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:ap-southeast-1:836503426071:userpool/ap-southeast-1_5hkd0Ax65
      - http:
          path: contacts/{id}
          method: delete
          request:
            parameters:
              paths:
                id: true
          cors: true
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:ap-southeast-1:836503426071:userpool/ap-southeast-1_5hkd0Ax65
  auth:
    handler: handler.auth
    #vpc: ${self:custom.vpc}
    timeout: 30
    events:
      - http:
          path: auth/register
          method: post
          cors: true
      - http:
          path: auth/login
          method: post
          cors: true
      - http:
          path: auth/verify
          method: post
          cors: true
